name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Repo Clone
        uses: actions/checkout@v4
      - name: Setup Node
        with:
          node-version: "18"
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Install dependencies
        run: npm ci
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo printing my name
        run: echo "My name is Gautam Jha"
